Repository clerk/clerk-docs, pull requests merged in 2024-02, with the labels that each got.

#675 Update manual-jwt.mdx
  docs/backend-requests/handling/manual-jwt.mdx
Labels: deploy-preview

#666 react updates v5
  docs/components/authentication/sign-in.mdx
  docs/components/authentication/sign-up.mdx
  docs/components/clerk-provider.mdx
  docs/components/control/authenticate-with-callback.mdx
  docs/components/control/redirect-to-signin.mdx
  docs/components/control/redirect-to-signup.mdx
  docs/components/customization/organization-profile.mdx
  docs/components/customization/overview.mdx
  docs/components/customization/user-profile.mdx
  docs/components/customization/variables.mdx
  docs/components/organization/create-organization.mdx
  docs/components/organization/organization-profile.mdx
  docs/components/unstyled/sign-in-button.mdx
  docs/components/unstyled/sign-out-button.mdx
  docs/components/unstyled/sign-up-button.mdx
  docs/components/user/user-button.mdx
  docs/components/user/user-profile.mdx
  docs/quickstarts/react.mdx
  docs/quickstarts/remix.mdx
  docs/references/backend/sessions/authenticate-request.mdx
  docs/references/javascript/clerk/clerk.mdx
  docs/references/javascript/clerk/create-organization.mdx
  docs/references/javascript/clerk/handle-navigation.mdx
  docs/references/javascript/clerk/organization-profile.mdx
  docs/references/javascript/clerk/sign-in.mdx
  docs/references/javascript/clerk/sign-up.mdx
  docs/references/javascript/clerk/user-button.mdx
  docs/references/javascript/clerk/user-profile.mdx
  docs/references/javascript/types/redirect-options.mdx
  docs/references/javascript/types/sign-in-redirect-options.mdx
  docs/references/javascript/types/sign-up-redirect-options.mdx
  docs/references/nextjs/custom-signup-signin-pages.mdx
  docs/references/react/add-react-router.mdx
Labels: deploy-preview

#674 authentication factor --> authentication strategy; remove unnecessary images
  docs/authentication/configuration/sign-in-options.mdx
  docs/authentication/configuration/sign-up-options.mdx
  docs/custom-flows/email-sms-otp.mdx
  docs/custom-flows/magic-links.mdx
  docs/custom-flows/user-impersonation.mdx
  public/images/authentication/email-address-verification.jpg
  public/images/authentication/email-address-verification.webp
  public/images/authentication/sms-verification.jpg
  public/images/authentication/sms-verification.webp
  public/images/custom-flows/authentication-strategies.jpg
  public/images/custom-flows/email-verification-link.jpg
  public/images/custom-flows/email-verification-link.webp
  public/images/custom-flows/impersonate-user.jpg
  public/images/custom-flows/impersonate-user.webp
Labels: deploy-preview

#671 feat: Add docs for X/Twitter v2 OAuth provider
  docs/authentication/social-connections/twitter.mdx
  docs/authentication/social-connections/x-twitter.mdx
  docs/manifest.json
  public/images/authentication-providers/x-twitter/fill-user-authentication-settings.webp
  public/images/authentication-providers/x-twitter/paste-credentials.webp
  public/images/authentication-providers/x-twitter/redirect-uri.webp
  public/images/authentication-providers/x-twitter/set-up-user-authentication-settings.webp
Labels: deploy-preview

#677 feat: Override types for roles and permissions
  docs/organizations/verify-user-permissions.mdx
Labels: deploy-preview

#681 DOCS-5150 update SignIn and useSignIn docs
  docs/references/javascript/sign-in/sign-in.mdx
  docs/references/react/use-sign-in.mdx
Labels: deploy-preview

#665 added nextauth migration guide
  docs/guides/authjs-migration.mdx
  docs/guides/overview.mdx
  docs/manifest.json
Labels: deploy-preview

#689 DOCS-5292 add missing property to SignUp; update useSignUp
  docs/references/javascript/sign-up/sign-up.mdx
  docs/references/react/use-sign-up.mdx
Labels: deploy-preview

#688 DOCS-5339 create references for has and protect helpers
  docs/backend-requests/resources/session-tokens.mdx
  docs/guides/force-organizations.mdx
  docs/organizations/create-roles-permissions.mdx
  docs/organizations/verify-user-permissions.mdx
  docs/references/nextjs/auth.mdx
  docs/references/nextjs/authentication-object.mdx
Labels: deploy-preview

#691 DOCS-699 fix broken injectkeys instances; add copy that explains injectkeys usage
  CONTRIBUTING.md
  docs/advanced-usage/using-proxies.mdx
  docs/backend-requests/handling/go.mdx
  docs/components/control/authenticate-with-callback.mdx
  docs/components/control/clerk-loaded.mdx
  docs/components/control/clerk-loading.mdx
  docs/components/control/multi-session.mdx
  docs/components/control/redirect-to-createorganization.mdx
  docs/components/control/redirect-to-organizationprofile.mdx
  docs/components/control/redirect-to-signin.mdx
  docs/components/control/redirect-to-signup.mdx
  docs/components/control/redirect-to-userprofile.mdx
  docs/components/control/signed-in.mdx
  docs/components/control/signed-out.mdx
  docs/integrations/databases/convex.mdx
  docs/integrations/databases/supabase.mdx
  docs/quickstarts/fastify.mdx
  docs/quickstarts/gatsby.mdx
  docs/quickstarts/javascript.mdx
  docs/quickstarts/nextjs.mdx
  docs/quickstarts/react.mdx
  docs/quickstarts/redwood.mdx
  docs/quickstarts/remix.mdx
  docs/references/go/overview.mdx
  docs/references/go/verifying-sessions.mdx
  docs/references/javascript/overview.mdx
  docs/references/nextjs/trpc.mdx
  docs/references/nodejs/overview.mdx
  docs/references/ruby/overview.mdx
Labels: deploy-preview

#700 DOCS-5152 Update User docs with an accurate list of user methods
  docs/references/javascript/clerk/sign-in.mdx
  docs/references/javascript/clerk/sign-up.mdx
  docs/references/javascript/user/user.mdx
Labels: deploy-preview

#703 DOCS-5376 Update Nextjs Quickstart
  docs/quickstarts/nextjs.mdx
Labels: deploy-preview

#701 New Upgrade Guide Structure
  docs/manifest.json
  docs/upgrade-guides/core-2/backend.mdx
  docs/upgrade-guides/core-2/chrome-extension.mdx
  docs/upgrade-guides/core-2/component-redesign.mdx
  docs/upgrade-guides/core-2/expo.mdx
  docs/upgrade-guides/core-2/fastify.mdx
  docs/upgrade-guides/core-2/javascript.mdx
  docs/upgrade-guides/core-2/nextjs.mdx
  docs/upgrade-guides/core-2/node.mdx
  docs/upgrade-guides/core-2/overview.mdx
  docs/upgrade-guides/core-2/react.mdx
  docs/upgrade-guides/core-2/remix.mdx
  docs/upgrade-guides/overview.mdx
  docs/upgrade-guides/sdk-versioning.mdx
  docs/upgrade-guides/upgrading-from-v4-to-v5.mdx
  docs/upgrade-guides/upgrading-nextjs-from-v4-to-v5.mdx
Labels: deploy-preview

#690 DOCS-676 abstract types from references pages
  docs/manifest.json
  docs/references/backend/sessions/get-session-list.mdx
  docs/references/javascript/organization-domain.mdx
  docs/references/javascript/session-with-activities.mdx
  docs/references/javascript/session.mdx
  docs/references/javascript/types/overview.mdx
  docs/references/javascript/types/session-status.mdx
  docs/references/javascript/user/create-metadata.mdx
  docs/references/javascript/user/password-management.mdx
  docs/references/javascript/user/totp.mdx
  docs/references/javascript/web3-wallet/verification.mdx
Labels: deploy-preview

#580 DOCS-627 Error documentation
  docs/errors/actor-tokens.mdx
  docs/errors/allowlist-identifiers.mdx
  docs/errors/application.mdx
  docs/errors/authentication.mdx
  docs/errors/backup-codes.mdx
  docs/errors/billing-accounts.mdx
  docs/errors/billing.mdx
  docs/errors/blocklist-identifiers.mdx
  docs/errors/clients.mdx
  docs/errors/cookie.mdx
  docs/errors/deprecation.mdx
  docs/errors/domains.mdx
  docs/errors/entitlements.mdx
  docs/errors/features.mdx
  docs/errors/identifications.mdx
  docs/errors/overview.mdx
  docs/errors/sign-in-tokens.mdx
  docs/errors/sign-in.mdx
  docs/errors/sign-up.mdx
  docs/manifest.json
Labels: deploy-preview, Blocked

#625 (WIP) Update error handling examples
  docs/custom-flows/error-handling.mdx
Labels: deploy-preview, Blocked

#698 Fix mountSignIn example
  docs/references/javascript/clerk/sign-in.mdx
Labels: Blocked

#711 Nextjs quickstart updates for Core 2
  docs/quickstarts/nextjs.mdx
Labels: deploy-preview

#715 (core1) DOCS-5394 Update React references
  docs/guides/force-organizations.mdx
  docs/references/react/use-auth.mdx
  docs/references/react/use-clerk.mdx
  docs/references/react/use-organization-list.mdx
  docs/references/react/use-organization.mdx
  docs/references/react/use-session-list.mdx
  docs/references/react/use-session.mdx
  docs/references/react/use-sign-in.mdx
  docs/references/react/use-sign-up.mdx
  docs/references/react/use-user.mdx
Labels: deploy-preview

#716 (core2) update authMiddleware references
  docs/account-portal/custom-redirects.mdx
  docs/advanced-usage/satellite-domains.mdx
  docs/backend-requests/overview.mdx
  docs/guides/authjs-migration.mdx
  docs/guides/force-organizations.mdx
  docs/references/nextjs/auth.mdx
  docs/references/nextjs/custom-signup-signin-pages.mdx
  docs/references/nextjs/read-session-data.mdx
  docs/references/nextjs/trpc.mdx
  docs/users/sync-data.mdx
Labels: deploy-preview

#726 DOCS-5441 (core2) update react quickstart
  docs/quickstarts/nextjs.mdx
  docs/quickstarts/react.mdx
  docs/upgrade-guides/core-2/nextjs.mdx
Labels: deploy-preview

#727 Verifying sessions in Go (review)
  docs/references/go/other-examples.mdx
  docs/references/go/overview.mdx
  docs/references/go/verifying-sessions.mdx
Labels: deploy-preview

#731 DOCS-5336 fix order of tabs in code example
  docs/users/metadata.mdx
Labels: deploy-preview

#738 add a note about the beta and linking to upgrade guide to quickstarts
  docs/quickstarts/expo.mdx
  docs/quickstarts/fastify.mdx
  docs/quickstarts/javascript.mdx
  docs/quickstarts/nextjs.mdx
  docs/quickstarts/react.mdx
  docs/quickstarts/remix.mdx
Labels: deploy-preview

#746 reorganize webhook docs
  docs/guides/authjs-migration.mdx
  docs/integrations/webhooks/inngest.mdx
  docs/integrations/webhooks/overview.mdx
  docs/integrations/webhooks/sync-data.mdx
  docs/manifest.json
Labels: deploy-preview

#747 Add callout to React hooks about opting in to resources
  docs/references/react/use-organization-list.mdx
  docs/references/react/use-organization.mdx
Labels: deploy-preview

#739 (core 1) update JS references for sign-in and sign-up
  docs/references/javascript/clerk/sign-in.mdx
  docs/references/javascript/clerk/sign-up.mdx
Labels: deploy-preview

#744 add getUserOAuthAccessToken to backend sdk
  docs/manifest.json
  docs/references/backend/types/paginated-resource-response.mdx
  docs/references/backend/user/get-user-oauth-access-token.mdx
Labels: deploy-preview

#712 Updated the documentation for Go SDK
  CONTRIBUTING.md
  docs/references/go/other-examples.mdx
  docs/references/go/overview.mdx
  docs/references/go/verifying-sessions.mdx
Labels: deploy-preview

#754 update Go overview; update manifest for consistency in title and sidenav title
  docs/manifest.json
  docs/references/go/overview.mdx
Labels: deploy-preview

#735 move redwood to community section
  docs/index.mdx
  docs/manifest.json
  docs/quickstarts/setup-clerk.mdx
  docs/references/redwood/overview.mdx
Labels: deploy-preview

#647 DOCS-5190 Create clerk middleware page
  docs/manifest.json
  docs/references/nextjs/clerk-middleware.mdx
  docs/references/nextjs/route-protection-requiring-authentication.mdx
  docs/references/nextjs/route-protection-requiring-authorization.mdx
Labels: deploy-preview

#755 Update Nextjs Quickstart examples
  docs/quickstarts/nextjs.mdx
Labels: deploy-preview
