Repository clerk/clerk-docs, pull requests merged in 2024-12, with the labels that each got.

#1753 (/organization-workspace) Fix broken link; update Dashboard navigation instructions
  docs/organizations/organization-workspaces.mdx
Labels: deploy-preview

#1747 Restore manual jwt verification example
  docs/_partials/authenticate-req.mdx
  docs/backend-requests/handling/manual-jwt.mdx
  docs/references/backend/authenticate-request.mdx
Labels: deploy-preview

#1761 Fix include
  docs/references/backend/authenticate-request.mdx
Labels: deploy-preview

#1763 Add React Router icon
  docs/index.mdx
Labels: deploy-preview

#1668 feat: Unauthorized sign-in
  docs/customization/account-portal/getting-started.mdx
  docs/customization/account-portal/overview.mdx
  docs/manifest.json
  docs/security/unauthorized-sign-in.mdx
  public/images/account-portal/unauthorized-sign-in.png
Labels: deploy-preview

#1774 chore: update captcha not enabled error message
  docs/errors/sign-up.mdx
Labels: deploy-preview

#1775 Fix reference in user metadata page
  docs/users/metadata.mdx
Labels: deploy-preview

#1776 Adds a reference to the cookie overflow warning in the dashboard
  docs/backend-requests/resources/session-tokens.mdx
Labels: deploy-preview

#1778 Quick Typo Fix
  docs/references/chrome-extension/sync-host.mdx
Labels: deploy-preview

#1666 update expo docs
  docs/_partials/expo/oauth-custom-flow.mdx
  docs/custom-flows/email-password-mfa.mdx
  docs/custom-flows/email-password.mdx
  docs/custom-flows/manage-totp-based-mfa.mdx
  docs/custom-flows/oauth-connections.mdx
  docs/custom-flows/sign-out.mdx
  docs/custom-flows/user-impersonation.mdx
  docs/guides/custom-types.mdx
  docs/manifest.json
  docs/quickstarts/expo.mdx
  docs/references/backend/types/backend-invitation.mdx
  docs/references/backend/types/backend-organization-invitation.mdx
  docs/references/backend/types/backend-organization-membership.mdx
  docs/references/backend/types/backend-organization.mdx
  docs/references/backend/types/backend-user.mdx
  docs/references/expo/overview.mdx
  docs/references/expo/read-session-user-data.mdx
  docs/references/expo/use-oauth.mdx
  docs/references/javascript/external-account.mdx
  docs/references/javascript/organization-invitation.mdx
  docs/references/javascript/organization-membership.mdx
  docs/references/javascript/organization/organization.mdx
  docs/references/javascript/sign-up/authenticate-with.mdx
  docs/references/javascript/sign-up/sign-up.mdx
  docs/references/javascript/types/metadata.mdx
  docs/references/javascript/types/oauth.mdx
  docs/references/javascript/types/user-organization-invitation.mdx
  docs/references/javascript/user/user.mdx
  docs/users/user-impersonation.mdx
Labels: deploy-preview

#1750 Update SignUp.unsafeMetadata description; update metadata guide
  docs/components/authentication/sign-up.mdx
  docs/users/metadata.mdx
Labels: deploy-preview, Blocked

#1785 Fix broken links on Enterprise SSO overview
  docs/authentication/enterprise-connections/overview.mdx
Labels: deploy-preview

#1770 Add docs for enterprise_sso and update examples
  docs/custom-flows/enterprise-connections.mdx
  docs/manifest.json
  docs/references/javascript/sign-in/authenticate-with.mdx
  docs/references/javascript/sign-up/authenticate-with.mdx
  docs/references/javascript/sign-up/verification.mdx
  docs/references/javascript/types/verification.mdx
Labels: deploy-preview

#1768 Introduce OKX Wallet Web3 provider and authentication strategy
  docs/authentication/configuration/sign-up-sign-in-options.mdx
  docs/customization/elements/reference/sign-in.mdx
  docs/references/javascript/clerk/clerk.mdx
  docs/references/javascript/sign-in/authenticate-with.mdx
  docs/references/javascript/sign-in/first-factor.mdx
  docs/references/javascript/sign-in/sign-in.mdx
  docs/references/javascript/sign-up/authenticate-with.mdx
  docs/references/javascript/sign-up/sign-up.mdx
  docs/references/javascript/sign-up/verification.mdx
  docs/references/javascript/sign-up/web3-verification.mdx
  docs/references/javascript/types/sign-in-first-factor.mdx
  docs/references/javascript/web3-wallet/verification.mdx
  docs/references/javascript/web3-wallet/web3-wallet.mdx
  docs/references/react/use-sign-in.mdx
  docs/users/web3.mdx
Labels: deploy-preview

#1786 fix: Remove snipped about xms_edov being in preview
  docs/authentication/enterprise-connections/easie/microsoft.mdx
Labels: deploy-preview

#1787 fix: typo in custom-session-token docs
  docs/backend-requests/making/custom-session-token.mdx
Labels: deploy-preview

#1723 feat: Add Force MFA Example
  docs/custom-flows/manage-totp-based-mfa.mdx
Labels: deploy-preview

#1789 chore: update page titles to "Clerk _Name_ SDK" for sdk reference overviews
  docs/references/astro/overview.mdx
  docs/references/chrome-extension/overview.mdx
  docs/references/expo/overview.mdx
  docs/references/javascript/overview.mdx
  docs/references/nextjs/overview.mdx
  docs/references/redwood/overview.mdx
  docs/references/tanstack-start/overview.mdx
Labels: deploy-preview

#1769 feat: Add docs for third party OIDC providers
  docs/authentication/enterprise-connections/oidc/custom-provider.mdx
  docs/authentication/enterprise-connections/overview.mdx
  docs/manifest.json
Labels: deploy-preview

#1767 feat: Add allowedRedirectProtocols documentation
  docs/components/clerk-provider.mdx
  docs/references/javascript/clerk/clerk.mdx
  docs/references/remix/clerk-app.mdx
Labels: deploy-preview

#1790 Update size limitation docs to reference only session tokens
  docs/backend-requests/making/jwt-templates.mdx
  docs/backend-requests/resources/session-tokens.mdx
Labels: deploy-preview

#1793 fix: clarify email address sign up requirements
  docs/authentication/configuration/sign-up-sign-in-options.mdx
Labels: deploy-preview

#1795 chore(testing-tokens): fix signup endpoint
  docs/testing/overview.mdx
Labels: deploy-preview

#1798 fix(testing): add note about running test setup in serial mode
  docs/testing/playwright/overview.mdx
Labels: deploy-preview

#1760 feat: Add React Router docs
  docs/_partials/react-hooks.mdx
  docs/index.mdx
  docs/manifest.json
  docs/manifest.schema.json
  docs/quickstarts/react-router.mdx
  docs/quickstarts/react.mdx
  docs/references/nextjs/auth-object.mdx
  docs/references/nextjs/overview.mdx
  docs/references/react-router/custom-signup-signin-pages.mdx
  docs/references/react-router/get-auth.mdx
  docs/references/react-router/library-mode.mdx
  docs/references/react-router/overview.mdx
  docs/references/react-router/read-session-data.mdx
  docs/references/react-router/root-auth-loader.mdx
  docs/references/react/add-react-router.mdx
  docs/references/react/overview.mdx
  docs/references/remix/custom-signup-signin-pages.mdx
  docs/telemetry.mdx
  docs/troubleshooting/create-a-minimal-reproduction.mdx
Labels: deploy-preview

#1781 Add the Expo Offline support page
  docs/manifest.json
  docs/manifest.schema.json
  docs/references/expo/offline-support.mdx
Labels: deploy-preview

#1771 feat: Add faq section to help address some common questions
  docs/references/chrome-extension/overview.mdx
Labels: deploy-preview

#1794 Expo Web sign-in-or-up docs
  docs/manifest.json
  docs/references/expo/web-support/custom-sign-in-or-up-page.mdx
  docs/references/expo/web-support/custom-sign-up-page.mdx
Labels: deploy-preview

#1792 TanStack Start sign-in-or-up docs
  docs/manifest.json
  docs/quickstarts/tanstack-start.mdx
  docs/references/tanstack-start/custom-sign-in-or-up-page.mdx
  docs/references/tanstack-start/custom-signup-page.mdx
Labels: deploy-preview

#1804 remove old api-keys doc
  docs/upgrade-guides/api-keys.mdx
Labels: Blocked

#1709 feat(vue): Introduce Vue SDK Quickstart
  docs/index.mdx
  docs/manifest.json
  docs/quickstarts/overview.mdx
  docs/quickstarts/vue.mdx
Labels: deploy-preview

#1735 How Clerk Works
  docs/how-clerk-works/cookies.mdx
  docs/how-clerk-works/overview.mdx
  docs/how-clerk-works/tokens-signatures.mdx
  docs/manifest.json
  public/images/how-clerk-works/cookie-no-domain.png
  public/images/how-clerk-works/cookie-with-domain.png
  public/images/how-clerk-works/devtools-cookies.png
  public/images/how-clerk-works/hybrid-auth-2.mp4
  public/images/how-clerk-works/hybrid-auth.mp4
  public/images/how-clerk-works/invalidation.mp4
  public/images/how-clerk-works/renewal.mp4
  public/images/how-clerk-works/stateful-auth-2.mp4
  public/images/how-clerk-works/stateful-auth.mp4
  public/images/how-clerk-works/stateless-auth-2.mp4
  public/images/how-clerk-works/stateless-auth.mp4
Labels: deploy-preview

#1808 docs(astro): Remove typescript declaration step
  docs/quickstarts/astro.mdx
Labels: deploy-preview

#1712 feat(vue): Add client helpers (part 2)
  docs/references/vue/use-organization.mdx
  docs/references/vue/use-session-list.mdx
  docs/references/vue/use-session.mdx
  docs/references/vue/use-sign-up.mdx
Labels: deploy-preview

#1810 (/custom-flows/error-handling) update guide
  docs/custom-flows/error-handling.mdx
Labels: deploy-preview

#1812 Add controls to "how clerk works" videos
  docs/how-clerk-works/overview.mdx
Labels: deploy-preview

#1777 Added appearance prop samples for hiding unsupported options
  docs/references/chrome-extension/sync-host.mdx
Labels: deploy-preview

#1820 fix: Update create enterprise OIDC label
  docs/authentication/enterprise-connections/oidc/custom-provider.mdx
Labels: deploy-preview

#1755 feat: SSO per org
  docs/authentication/enterprise-connections/authentication-flows.mdx
  docs/authentication/enterprise-connections/easie/google.mdx
  docs/authentication/enterprise-connections/easie/microsoft.mdx
  docs/authentication/enterprise-connections/oidc/custom-provider.mdx
  docs/authentication/enterprise-connections/saml/azure.mdx
  docs/authentication/enterprise-connections/saml/custom-provider.mdx
  docs/authentication/enterprise-connections/saml/google.mdx
  docs/authentication/enterprise-connections/saml/okta.mdx
  docs/manifest.json
  docs/organizations/manage-sso.mdx
  docs/organizations/overview.mdx
  docs/organizations/verified-domains.mdx
  docs/references/backend/saml-connections/create-saml-connection.mdx
  docs/references/backend/saml-connections/update-saml-connection.mdx
Labels: deploy-preview

#1823 chore: Remove Astro from Community SDKs list
  docs/manifest.json
Labels: deploy-preview

#1827 (custom-session-token) add usage info for non-nextjs frameworks
  docs/backend-requests/making/custom-session-token.mdx
Labels: deploy-preview

#1828 Add legalAcceptedAt and skipLegalChecks fields to user management methods
  docs/references/backend/types/backend-user.mdx
  docs/references/backend/user/create-user.mdx
  docs/references/backend/user/get-user-list.mdx
  docs/references/backend/user/get-user.mdx
  docs/references/backend/user/update-user.mdx
  docs/references/javascript/user/user.mdx
Labels: deploy-preview

#1814 (chore) align React and Vue docs; align prop/param descriptions
  docs/references/astro/auth-store.mdx
  docs/references/backend/invitations/create-invitation.mdx
  docs/references/backend/organization/create-organization-invitation.mdx
  docs/references/backend/organization/create-organization-membership.mdx
  docs/references/backend/organization/create-organization.mdx
  docs/references/backend/organization/delete-organization-membership.mdx
  docs/references/backend/organization/update-organization-membership-metadata.mdx
  docs/references/backend/organization/update-organization-membership.mdx
  docs/references/backend/organization/update-organization-metadata.mdx
  docs/references/backend/organization/update-organization.mdx
  docs/references/backend/sign-in-tokens/create-sign-in-token.mdx
  docs/references/backend/types/backend-allowlist-identifier.mdx
  docs/references/backend/types/backend-client.mdx
  docs/references/backend/types/backend-invitation.mdx
  docs/references/backend/types/backend-organization-invitation.mdx
  docs/references/backend/types/backend-organization-membership.mdx
  docs/references/backend/types/backend-organization.mdx
  docs/references/backend/types/backend-redirect-url.mdx
  docs/references/backend/types/backend-session.mdx
  docs/references/backend/types/backend-user.mdx
  docs/references/backend/types/saml-connection.mdx
  docs/references/backend/user/create-user.mdx
  docs/references/backend/user/get-count.mdx
  docs/references/backend/user/get-user-oauth-access-token.mdx
  docs/references/backend/user/update-user-metadata.mdx
  docs/references/backend/user/update-user.mdx
  docs/references/javascript/client.mdx
  docs/references/javascript/email-address.mdx
  docs/references/javascript/external-account.mdx
  docs/references/javascript/organization-domain.mdx
  docs/references/javascript/organization-invitation.mdx
  docs/references/javascript/organization-membership-request.mdx
  docs/references/javascript/organization-membership.mdx
  docs/references/javascript/organization/members.mdx
  docs/references/javascript/organization/organization.mdx
  docs/references/javascript/phone-number.mdx
  docs/references/javascript/session-with-activities.mdx
  docs/references/javascript/session.mdx
  docs/references/javascript/sign-in/first-factor.mdx
  docs/references/javascript/types/metadata.mdx
  docs/references/javascript/types/passkey-resource.mdx
  docs/references/javascript/types/user-organization-invitation.mdx
  docs/references/javascript/user/totp.mdx
  docs/references/javascript/user/user.mdx
  docs/references/javascript/web3-wallet/web3-wallet.mdx
  docs/references/nextjs/auth-object.mdx
  docs/references/react-router/get-auth.mdx
  docs/references/react/use-auth.mdx
  docs/references/react/use-clerk.mdx
  docs/references/react/use-organization-list.mdx
  docs/references/react/use-organization.mdx
  docs/references/react/use-reverification.mdx
  docs/references/react/use-session-list.mdx
  docs/references/react/use-session.mdx
  docs/references/react/use-sign-in.mdx
  docs/references/react/use-sign-up.mdx
  docs/references/react/use-user.mdx
Labels: deploy-preview

#1728 feat(nuxt): Add Nuxt SDK docs
  docs/_partials/nuxt/use-auth.mdx
  docs/index.mdx
  docs/manifest.json
  docs/manifest.schema.json
  docs/quickstarts/nuxt.mdx
  docs/quickstarts/overview.mdx
  docs/references/backend/overview.mdx
  docs/references/nuxt/clerk-middleware.mdx
  docs/references/nuxt/overview.mdx
  docs/references/nuxt/protect-pages.mdx
  docs/references/nuxt/read-session-data.mdx
Labels: deploy-preview

#1815 chore: align reference headings, descriptions, structure
  docs/references/astro/overview.mdx
  docs/references/chrome-extension/overview.mdx
  docs/references/expo/overview.mdx
  docs/references/express/overview.mdx
  docs/references/go/overview.mdx
  docs/references/ios/overview.mdx
  docs/references/nextjs/overview.mdx
  docs/references/react-router/overview.mdx
  docs/references/react/overview.mdx
  docs/references/redwood/overview.mdx
  docs/references/tanstack-start/overview.mdx
Labels: deploy-preview

#1634 Add organizationSyncOptions prop to clerkMiddleware() options
  docs/references/nextjs/clerk-middleware.mdx
Labels: deploy-preview

#1664 DX Guide: Using Organization Slugs in URLs
  docs/manifest.json
  docs/organizations/org-slugs-in-urls.mdx
Labels: deploy-preview

#1826 Add disable bot protection step to native sdk quickstarts
  docs/quickstarts/chrome-extension.mdx
  docs/quickstarts/expo.mdx
  docs/quickstarts/ios.mdx
Labels: deploy-preview

#1830 chore: (authentication/web3/coinbase-wallet) align with metamask and okx
  docs/authentication/web3/coinbase-wallet.mdx
Labels: deploy-preview

#1817 feat: OKX Wallet Web3 authentication guide
  docs/authentication/web3/okx-wallet.mdx
  docs/manifest.json
Labels: deploy-preview

#1818 feat: MetaMask Web3 authentication guide
  docs/authentication/web3/metamask.mdx
  docs/manifest.json
Labels: deploy-preview

#1829 add a section on testing flow for getting valid session tokens
  docs/testing/overview.mdx
Labels: deploy-preview

#1710 feat(vue,nuxt): Add Vue and Nuxt SDK docs
  docs/_partials/vue-nuxt/composables.mdx
  docs/_partials/vue-nuxt/use-auth.mdx
  docs/index.mdx
  docs/manifest.json
  docs/manifest.schema.json
  docs/quickstarts/nuxt.mdx
  docs/quickstarts/overview.mdx
  docs/quickstarts/vue.mdx
  docs/references/backend/overview.mdx
  docs/references/nuxt/clerk-middleware.mdx
  docs/references/nuxt/overview.mdx
  docs/references/nuxt/protect-pages.mdx
  docs/references/nuxt/read-session-data.mdx
  docs/references/react/use-user.mdx
  docs/references/vue/migrating-from-vue-community-sdk.mdx
  docs/references/vue/overview.mdx
  docs/references/vue/use-auth.mdx
  docs/references/vue/use-clerk.mdx
  docs/references/vue/use-organization.mdx
  docs/references/vue/use-session-list.mdx
  docs/references/vue/use-session.mdx
  docs/references/vue/use-sign-in.mdx
  docs/references/vue/use-sign-up.mdx
  docs/references/vue/use-user.mdx
Labels: deploy-preview

#1806 fix(expo-offline-support): Add `Handling network errors` section
  docs/references/expo/offline-support.mdx
Labels: deploy-preview

#1813 feat: Added doc for for web server deployment
  docs/deployments/deploy-behind-a-proxy.mdx
  docs/manifest.json
Labels: deploy-preview
