Repository clerk/clerk-docs, pull requests merged in 2024-08, with the labels that each got.

#1352 Use `nginx` lang for nginx config code snippet
  docs/advanced-usage/using-proxies.mdx
Labels: deploy-preview

#1178 (/organizations/overview): update allow users to create organization path
  docs/organizations/overview.mdx
Labels: Blocked

#1347 Correct broken links
  docs/custom-flows/user-impersonation.mdx
  docs/integrations/databases/neon.mdx
Labels: deploy-preview

#1355 Change Custom Flow Swift Code Blocks to 2 Spaces
  docs/custom-flows/add-email.mdx
  docs/custom-flows/add-phone.mdx
  docs/custom-flows/email-password-mfa.mdx
  docs/custom-flows/email-password.mdx
  docs/custom-flows/email-sms-otp.mdx
  docs/custom-flows/forgot-password.mdx
  docs/custom-flows/oauth-connections.mdx
  docs/custom-flows/sign-out.mdx
Labels: deploy-preview

#1332 Add image to the debugging webhooks doc
  docs/integrations/webhooks/debug-your-webhooks.mdx
  public/images/integrations/webhooks/webhooks_diagram.png
Labels: deploy-preview

#1346 Add cookies section on the SDK spec terminology
  docs/references/sdk/terminology.mdx
Labels: deploy-preview

#1302 Add docs for Custom menu items for UserButton
  docs/components/customization/user-button.mdx
  docs/components/user/user-button.mdx
  docs/manifest.json
  docs/references/javascript/types/custom-menu-item.mdx
Labels: deploy-preview

#1367 Fix lists on Neon page
  docs/integrations/databases/neon.mdx
Labels: deploy-preview

#1345 feat(deployments): Migrate from Cognito
  docs/deployments/migrate-from-cognito.mdx
  docs/manifest.json
Labels: deploy-preview

#1369 Add layout.unsafe_disableDevelopmentModeWarnings property to appearance
  docs/components/customization/layout.mdx
Labels: deploy-preview

#1376 rename .social to .oauth in ios oauth custom flow
  docs/custom-flows/oauth-connections.mdx
Labels: deploy-preview

#1374 (/email-sms-otp) Remove setError call in code example
  docs/custom-flows/email-sms-otp.mdx
Labels: deploy-preview

#1375 Align Cypress and Playwright guides
  docs/testing/cypress.mdx
  docs/testing/playwright.mdx
Labels: deploy-preview

#1373 (/custom-flows/overview) add callout pointing users to guides
  docs/custom-flows/overview.mdx
Labels: deploy-preview

#1370 Update demo repo callouts for Cypress and Supabase guides
  docs/integrations/databases/supabase.mdx
  docs/testing/cypress.mdx
Labels: deploy-preview

#1360 (/webhooks/inngest) Fix code example
  docs/integrations/webhooks/inngest.mdx
Labels: deploy-preview

#1358 (/redirect-to-userprofile) Add instructions for configuring user profile URL
  docs/components/control/redirect-to-userprofile.mdx
Labels: deploy-preview

#1378 Enable Prettier for code blocks: `backend-requests`
  docs/backend-requests/handling/gatsby.mdx
  docs/backend-requests/handling/go.mdx
  docs/backend-requests/handling/manual-jwt.mdx
  docs/backend-requests/handling/nodejs.mdx
  docs/backend-requests/handling/ruby-rails.mdx
  docs/backend-requests/making/cross-origin.mdx
  docs/backend-requests/making/custom-session-token.mdx
  docs/backend-requests/making/jwt-templates.mdx
  docs/backend-requests/making/same-origin.mdx
Labels: deploy-preview

#1377 Enable Prettier for code blocks: `account-portal`, `advanced-usage`, `authentication`
  docs/account-portal/getting-started.mdx
  docs/advanced-usage/clerk-idp.mdx
  docs/advanced-usage/satellite-domains.mdx
  docs/advanced-usage/using-proxies.mdx
  docs/authentication/social-connections/oauth.mdx
Labels: deploy-preview

#1380 Enable Prettier for code blocks: `custom-flows`
  docs/custom-flows/email-links.mdx
  docs/custom-flows/email-sms-otp.mdx
  docs/custom-flows/embedded-email-links.mdx
  docs/custom-flows/error-handling.mdx
  docs/custom-flows/forgot-password.mdx
  docs/custom-flows/google-one-tap.mdx
  docs/custom-flows/invitations.mdx
  docs/custom-flows/multi-session-applications.mdx
  docs/custom-flows/passkeys.mdx
  docs/custom-flows/saml-connections.mdx
  docs/custom-flows/sign-out.mdx
Labels: deploy-preview

#1384 Enable Prettier for code blocks: `integrations`
  docs/integrations/databases/convex.mdx
  docs/integrations/databases/fauna.mdx
  docs/integrations/databases/firebase.mdx
  docs/integrations/databases/grafbase.mdx
  docs/integrations/databases/hasura.mdx
  docs/integrations/databases/neon.mdx
  docs/integrations/databases/nhost.mdx
  docs/integrations/databases/supabase.mdx
  docs/integrations/webhooks/debug-your-webhooks.mdx
  docs/integrations/webhooks/inngest.mdx
  docs/integrations/webhooks/overview.mdx
  docs/integrations/webhooks/sync-data.mdx
Labels: deploy-preview

#1381 Enable Prettier for code blocks: `deployments`, `elements`
  docs/deployments/changing-domains.mdx
  docs/deployments/migrate-from-firebase.mdx
  docs/deployments/migrate-overview.mdx
  docs/elements/examples/primitives.mdx
  docs/elements/examples/shadcn-ui.mdx
  docs/elements/examples/sign-in.mdx
  docs/elements/examples/sign-up.mdx
  docs/elements/guides/sign-in.mdx
  docs/elements/guides/sign-up.mdx
  docs/elements/guides/styling.mdx
  docs/elements/overview.mdx
  docs/elements/reference/common.mdx
  docs/elements/reference/sign-in.mdx
  docs/elements/reference/sign-up.mdx
Labels: deploy-preview

#1382 Enable Prettier for code blocks: `errors`
  docs/errors/actor-tokens.mdx
  docs/errors/allowlist-identifiers.mdx
  docs/errors/application.mdx
  docs/errors/authentication.mdx
  docs/errors/backup-codes.mdx
  docs/errors/billing-accounts.mdx
  docs/errors/billing.mdx
  docs/errors/blocklist-identifiers.mdx
  docs/errors/clients.mdx
  docs/errors/cookie.mdx
  docs/errors/deprecation.mdx
  docs/errors/domains.mdx
  docs/errors/entitlements.mdx
  docs/errors/features.mdx
  docs/errors/identifications.mdx
  docs/errors/sign-in-tokens.mdx
  docs/errors/sign-in.mdx
  docs/errors/sign-up.mdx
Labels: deploy-preview

#1383 Enable Prettier for code blocks: `guides`
  docs/guides/add-onboarding-flow.mdx
  docs/guides/authjs-migration.mdx
  docs/guides/basic-rbac.mdx
  docs/guides/custom-redirects.mdx
  docs/guides/force-organizations.mdx
  docs/guides/image-optimization/imageurl-image-optimization.mdx
Labels: deploy-preview

#1385 rename socialprovider to oauthprovider
  docs/custom-flows/oauth-connections.mdx
Labels: deploy-preview

#1330 docs(elements): Add docs for `FieldState` `config` field
  docs/elements/reference/common.mdx
Labels: deploy-preview

#1389 Enable Prettier for code blocks: `organizations`
  docs/organizations/creating-organizations.mdx
  docs/organizations/custom-organization-switcher.mdx
  docs/organizations/inviting-users.mdx
  docs/organizations/manage-invitations.mdx
  docs/organizations/manage-membership-requests.mdx
  docs/organizations/managing-roles.mdx
  docs/organizations/updating-organizations.mdx
  docs/organizations/verified-domains.mdx
  docs/organizations/verify-user-permissions.mdx
  docs/organizations/viewing-memberships.mdx
Labels: deploy-preview

#1390 Enable Prettier for code blocks: `quickstarts`
  docs/quickstarts/astro.mdx
  docs/quickstarts/fastify.mdx
  docs/quickstarts/gatsby.mdx
  docs/quickstarts/javascript.mdx
  docs/quickstarts/nextjs.mdx
  docs/quickstarts/react.mdx
  docs/quickstarts/remix.mdx
Labels: deploy-preview

#1391 Enable Prettier for code blocks: `telemetry`, `security`, `testing`, `troubleshooting`
  docs/security/clerk-csp.mdx
  docs/telemetry.mdx
  docs/testing/overview.mdx
  docs/testing/playwright.mdx
  docs/testing/postman-or-insomnia.mdx
  docs/testing/test-emails-and-phones.mdx
  docs/troubleshooting/email-deliverability.mdx
  docs/troubleshooting/script-loading.mdx
Labels: deploy-preview

#1392 Enable Prettier for code blocks: `upgrade-guides`, `users`
  docs/upgrade-guides/core-2/backend.mdx
  docs/upgrade-guides/core-2/chrome-extension.mdx
  docs/upgrade-guides/core-2/component-redesign.mdx
  docs/upgrade-guides/core-2/expo.mdx
  docs/upgrade-guides/core-2/fastify.mdx
  docs/upgrade-guides/core-2/javascript.mdx
  docs/upgrade-guides/core-2/nextjs.mdx
  docs/upgrade-guides/core-2/node.mdx
  docs/upgrade-guides/core-2/react.mdx
  docs/upgrade-guides/core-2/remix.mdx
  docs/upgrade-guides/upgrading-from-v2-to-v3.mdx
  docs/upgrade-guides/url-based-session-syncing.mdx
  docs/users/deleting-users.mdx
  docs/users/invitations.mdx
  docs/users/metadata.mdx
  docs/users/web3.mdx
Labels: deploy-preview

#1359 Rename Expo read-session-user-data doc; remove unused import
  docs/manifest.json
  docs/quickstarts/expo.mdx
  docs/references/expo/read-session-user-data.mdx
Labels: deploy-preview

#1336 iOS: Quickstart
  docs/manifest.json
  docs/manifest.schema.json
  docs/quickstarts/ios.mdx
  docs/quickstarts/overview.mdx
  docs/references/ios/overview.mdx
Labels: deploy-preview

#1386 Add hideSlug prop definition to Organization components
  docs/components/organization/create-organization.mdx
  docs/components/organization/organization-list.mdx
  docs/components/organization/organization-switcher.mdx
Labels: deploy-preview

#1398 chore(elements): Add captcha usage to examples
  docs/elements/examples/shadcn-ui.mdx
  docs/elements/examples/sign-up.mdx
  docs/elements/guides/sign-up.mdx
  docs/elements/reference/sign-up.mdx
Labels: deploy-preview

#1402 Enable Prettier for code blocks: `references/javascript`
  docs/references/javascript/clerk/build-urls.mdx
  docs/references/javascript/clerk/clerk.mdx
  docs/references/javascript/clerk/handle-navigation.mdx
  docs/references/javascript/clerk/organization-methods.mdx
  docs/references/javascript/clerk/redirect-methods.mdx
  docs/references/javascript/clerk/session-methods.mdx
  docs/references/javascript/client.mdx
  docs/references/javascript/email-address.mdx
  docs/references/javascript/external-account.mdx
  docs/references/javascript/organization-domain.mdx
  docs/references/javascript/organization-invitation.mdx
  docs/references/javascript/organization-membership-request.mdx
  docs/references/javascript/organization-membership.mdx
  docs/references/javascript/organization/domains.mdx
  docs/references/javascript/organization/invitations.mdx
  docs/references/javascript/organization/members.mdx
  docs/references/javascript/organization/membership-request.mdx
  docs/references/javascript/organization/organization.mdx
  docs/references/javascript/phone-number.mdx
  docs/references/javascript/session-with-activities.mdx
  docs/references/javascript/session.mdx
  docs/references/javascript/sign-in/authenticate-with.mdx
  docs/references/javascript/sign-in/first-factor.mdx
  docs/references/javascript/sign-in/second-factor.mdx
  docs/references/javascript/sign-in/sign-in.mdx
  docs/references/javascript/sign-up/authenticate-with.mdx
  docs/references/javascript/sign-up/email-verification.mdx
  docs/references/javascript/sign-up/phone-verification.mdx
  docs/references/javascript/sign-up/sign-up.mdx
  docs/references/javascript/sign-up/verification.mdx
  docs/references/javascript/sign-up/web3-verification.mdx
  docs/references/javascript/types/oauth.mdx
  docs/references/javascript/types/overview.mdx
  docs/references/javascript/types/session-status.mdx
  docs/references/javascript/types/sign-in-first-factor.mdx
  docs/references/javascript/types/sign-in-second-factor.mdx
  docs/references/javascript/types/user-organization-invitation.mdx
  docs/references/javascript/types/verification.mdx
  docs/references/javascript/user/create-metadata.mdx
  docs/references/javascript/user/password-management.mdx
  docs/references/javascript/user/totp.mdx
  docs/references/javascript/user/user.mdx
  docs/references/javascript/web3-wallet/verification.mdx
  docs/references/javascript/web3-wallet/web3-wallet.mdx
Labels: deploy-preview

#1403 Enable Prettier for code blocks: `references/backend`
  docs/references/backend/allowlist/create-allowlist-identifier.mdx
  docs/references/backend/allowlist/delete-allowlist-identifier.mdx
  docs/references/backend/allowlist/get-allowlist-identifier-list.mdx
  docs/references/backend/authenticate-request.mdx
  docs/references/backend/client/get-client-list.mdx
  docs/references/backend/client/get-client.mdx
  docs/references/backend/client/verify-client.mdx
  docs/references/backend/domains/delete-domain.mdx
  docs/references/backend/email-addresses/create-email-address.mdx
  docs/references/backend/email-addresses/delete-email-address.mdx
  docs/references/backend/email-addresses/get-email-address.mdx
  docs/references/backend/invitations/create-invitation.mdx
  docs/references/backend/invitations/get-invitation-list.mdx
  docs/references/backend/invitations/revoke-invitation.mdx
  docs/references/backend/organization/create-organization-invitation.mdx
  docs/references/backend/organization/create-organization-membership.mdx
  docs/references/backend/organization/create-organization.mdx
  docs/references/backend/organization/delete-organization-logo.mdx
  docs/references/backend/organization/delete-organization-membership.mdx
  docs/references/backend/organization/delete-organization.mdx
  docs/references/backend/organization/get-organization-invitation-list.mdx
  docs/references/backend/organization/get-organization-invitation.mdx
  docs/references/backend/organization/get-organization-list.mdx
  docs/references/backend/organization/get-organization-membership-list.mdx
  docs/references/backend/organization/get-organization.mdx
  docs/references/backend/organization/update-organization-logo.mdx
  docs/references/backend/overview.mdx
  docs/references/backend/phone-numbers/create-phone-number.mdx
  docs/references/backend/phone-numbers/delete-phone-number.mdx
  docs/references/backend/phone-numbers/get-phone-number.mdx
  docs/references/backend/redirect-urls/create-redirect-url.mdx
  docs/references/backend/redirect-urls/delete-redirect-url.mdx
  docs/references/backend/redirect-urls/get-redirect-url-list.mdx
  docs/references/backend/redirect-urls/get-redirect-url.mdx
  docs/references/backend/saml-connections/create-saml-connection.mdx
  docs/references/backend/saml-connections/delete-saml-connection.mdx
  docs/references/backend/saml-connections/get-saml-connection-list.mdx
  docs/references/backend/saml-connections/get-saml-connection.mdx
  docs/references/backend/sessions/get-session-list.mdx
  docs/references/backend/sessions/get-session.mdx
  docs/references/backend/sessions/get-token.mdx
  docs/references/backend/sessions/revoke-session.mdx
  docs/references/backend/sessions/verify-session.mdx
  docs/references/backend/sign-in-tokens/create-sign-in-token.mdx
  docs/references/backend/sign-in-tokens/revoke-sign-in-token.mdx
  docs/references/backend/testing-tokens/create-testing-token.mdx
  docs/references/backend/user/delete-user.mdx
  docs/references/backend/user/disable-user-mfa.mdx
  docs/references/backend/user/get-count.mdx
  docs/references/backend/user/get-organization-membership-list.mdx
  docs/references/backend/user/get-user-list.mdx
  docs/references/backend/user/get-user-oauth-access-token.mdx
  docs/references/backend/user/get-user.mdx
  docs/references/backend/user/update-user-profile-image.mdx
  docs/references/backend/user/update-user.mdx
  docs/references/backend/user/verify-password.mdx
  docs/references/backend/user/verify-totp.mdx
  docs/references/backend/verify-token.mdx
Labels: deploy-preview

#1404 Enable Prettier for code blocks: `references/{expo,gatsby,go,nextjs,nodejs,redwood,ruby}`
  docs/references/expo/read-session-user-data.mdx
  docs/references/gatsby/with-server-auth.mdx
  docs/references/go/other-examples.mdx
  docs/references/go/overview.mdx
  docs/references/go/verifying-sessions.mdx
  docs/references/nextjs/auth-middleware.mdx
  docs/references/nextjs/auth-object.mdx
  docs/references/nextjs/auth.mdx
  docs/references/nextjs/build-clerk-props.mdx
  docs/references/nextjs/clerk-middleware.mdx
  docs/references/nextjs/current-user.mdx
  docs/references/nextjs/custom-signup-signin-pages.mdx
  docs/references/nextjs/get-auth.mdx
  docs/references/nextjs/read-session-data.mdx
  docs/references/nextjs/route-handlers.mdx
  docs/references/nextjs/server-actions.mdx
  docs/references/nextjs/trpc.mdx
  docs/references/nextjs/usage-with-older-versions.mdx
  docs/references/nodejs/available-methods.mdx
  docs/references/nodejs/overview.mdx
  docs/references/redwood/overview.mdx
  docs/references/ruby/available-methods.mdx
  docs/references/ruby/overview.mdx
  docs/references/ruby/rack-rails.mdx
Labels: deploy-preview

#1405 Enable Prettier for code blocks: `references/{astro,react,remix}`
  docs/references/astro/auth-store.mdx
  docs/references/astro/clerk-middleware.mdx
  docs/references/astro/clerk-store.mdx
  docs/references/astro/endpoints.mdx
  docs/references/astro/locals.mdx
  docs/references/astro/migrating-from-astro-community-sdk.mdx
  docs/references/astro/organization-store.mdx
  docs/references/astro/react.mdx
  docs/references/astro/read-session-data.mdx
  docs/references/astro/session-list-store.mdx
  docs/references/astro/session-store.mdx
  docs/references/astro/sign-in-store.mdx
  docs/references/astro/sign-up-store.mdx
  docs/references/astro/user-store.mdx
  docs/references/react/add-react-router.mdx
  docs/references/react/use-auth.mdx
  docs/references/react/use-clerk.mdx
  docs/references/react/use-organization-list.mdx
  docs/references/react/use-organization.mdx
  docs/references/react/use-session-list.mdx
  docs/references/react/use-session.mdx
  docs/references/react/use-sign-in.mdx
  docs/references/react/use-sign-up.mdx
  docs/references/react/use-user.mdx
  docs/references/remix/custom-signup-signin-pages.mdx
  docs/references/remix/read-session-data.mdx
  docs/references/remix/spa-mode.mdx
Labels: deploy-preview

#1395 SDK Spec: Fullstack
  docs/references/sdk/fullstack.mdx
Labels: deploy-preview

#1368 SDK Spec: Frontend-only
  docs/references/sdk/frontend-only.mdx
  docs/references/sdk/terminology.mdx
  docs/references/sdk/types.mdx
Labels: deploy-preview

#1399 Expo: Add reference and usage guide for useLocalCredentials
  docs/manifest.json
  docs/references/expo/local-credentials.mdx
  docs/references/expo/use-local-credentials.mdx
Labels: deploy-preview

#1394 SDK Spec: Backend-only
  docs/references/sdk/backend-only.mdx
Labels: deploy-preview

#1419 Fix nested list on "OAuth with a custom auth provider" page
  docs/authentication/social-connections/custom-provider.mdx
Labels: deploy-preview

#1420 Fix manifest structure
  docs/manifest.json
Labels: deploy-preview

#1412 docs: add step to custom sign up pages and routes about adding routes to be ignored by middleware
  docs/references/nextjs/custom-signup-signin-pages.mdx
Labels: deploy-preview

#1422 Correct broken link to roles page
  docs/organizations/creator-role.mdx
Labels: deploy-preview

#1421 Kenton/docs 8972 update docsreferencesnextjscustom signup signin pages
  docs/references/nextjs/custom-signup-signin-pages.mdx
Labels: deploy-preview

#1387 iOS: getToken()
  docs/manifest.json
  docs/references/ios/get-token.mdx
Labels: deploy-preview

#1364 ORGS-111: Add docs for the new `createOrganizationsLimit` field
  docs/organizations/overview.mdx
  docs/references/backend/types/backend-user.mdx
  docs/references/backend/user/update-user.mdx
  docs/references/javascript/user/user.mdx
Labels: deploy-preview, Blocked

#1432 Fix syntax errors in higher order component code snippets
  docs/upgrade-guides/core-2/nextjs.mdx
  docs/upgrade-guides/core-2/react.mdx
Labels: deploy-preview

#1410 (/clerk-provider) Update info about dynamic rendering
  docs/components/clerk-provider.mdx
Labels: deploy-preview

#1430 fix: Add callout for 'use client' directive
  docs/customization/organization-profile.mdx
  docs/customization/user-button.mdx
  docs/customization/user-profile.mdx
Labels: deploy-preview

#1344 Clerk SDK Spec
  docs/manifest.json
  docs/references/sdk/backend-only.mdx
  docs/references/sdk/conventions.mdx
  docs/references/sdk/frontend-only.mdx
  docs/references/sdk/fullstack.mdx
  docs/references/sdk/overview.mdx
  docs/references/sdk/philosophy.mdx
  docs/references/sdk/terminology.mdx
  docs/references/sdk/types.mdx
Labels: deploy-preview

#1408 Add conditional rendering example to UserButton menu items
  docs/customization/user-button.mdx
Labels: deploy-preview

#1444 fixing link to staging-alternatives in staging doc
  docs/deployments/set-up-staging.mdx
Labels: deploy-preview

#1434 docs(astro): Add multi-framework example for $authStore and $clerkStore
  docs/references/astro/auth-store.mdx
  docs/references/astro/clerk-store.mdx
Labels: deploy-preview

#1443 docs(astro): Add multi-framework example for $session and $sessionListStore
  docs/references/astro/session-list-store.mdx
  docs/references/astro/session-store.mdx
Labels: deploy-preview

#1441 docs(astro): Add multi-framework example for $userStore
  docs/references/astro/user-store.mdx
Labels: deploy-preview

#1435 docs(astro): Add multi-framework example for $signInStore and $signUpStore
  docs/references/astro/sign-in-store.mdx
  docs/references/astro/sign-up-store.mdx
Labels: deploy-preview

#1438 docs(astro): Add multi-framework example for $organizationStore
  docs/references/astro/organization-store.mdx
Labels: deploy-preview

#1448 Fix sub-list indentation
  docs/custom-flows/email-links.mdx
  docs/guides/add-onboarding-flow.mdx
  docs/guides/authjs-migration.mdx
  docs/organizations/verify-user-permissions.mdx
  docs/quickstarts/astro.mdx
  docs/quickstarts/javascript.mdx
  docs/quickstarts/nextjs.mdx
  docs/quickstarts/react.mdx
  docs/references/nextjs/auth-middleware.mdx
  docs/references/remix/spa-mode.mdx
Labels: deploy-preview

#1449 Replace tables with `<Properties>`
  docs/components/authentication/google-one-tap.mdx
  docs/components/authentication/sign-in.mdx
  docs/custom-flows/overview.mdx
  docs/references/backend/types/paginated-resource-response.mdx
  docs/references/javascript/clerk/clerk.mdx
  docs/references/nextjs/get-auth.mdx
Labels: deploy-preview

#1450 Add a card for the ios sdk to the docs home
  docs/index.mdx
  docs/quickstarts/overview.mdx
  docs/references/ios/overview.mdx
Labels: deploy-preview

#1455 Tweak home page logo size
  docs/index.mdx
Labels: deploy-preview

#1456 Remove "Community" tag from nav items under "Community SDKs"
  docs/manifest.json
Labels: deploy-preview

#1401 feat: Adds docs on the new tranferable prop
  docs/components/authentication/sign-in.mdx
  docs/references/javascript/clerk/handle-navigation.mdx
Labels: deploy-preview

#1454 docs(astro): Add authentication and user components references
  docs/components/authentication/google-one-tap.mdx
  docs/components/authentication/sign-in.mdx
  docs/components/authentication/sign-up.mdx
  docs/components/user/user-button.mdx
  docs/components/user/user-profile.mdx
Labels: deploy-preview

#1453 docs(astro): Add organization components references
  docs/components/organization/create-organization.mdx
  docs/components/organization/organization-list.mdx
  docs/components/organization/organization-profile.mdx
  docs/components/organization/organization-switcher.mdx
Labels: deploy-preview

#1452 docs(astro): Add unstyled component references
  docs/components/unstyled/sign-in-button.mdx
  docs/components/unstyled/sign-out-button.mdx
  docs/components/unstyled/sign-up-button.mdx
Labels: deploy-preview

#1451 docs(astro): Add control components references
  docs/components/control/signed-in.mdx
  docs/components/control/signed-out.mdx
  docs/components/protect.mdx
Labels: deploy-preview

#1460 Drop warning for custom OAuth providers
  docs/authentication/social-connections/custom-provider.mdx
Labels: deploy-preview

#1467 Add Remix icon to quickstart hero
  docs/quickstarts/remix.mdx
Labels: deploy-preview

#1462 Create guide on overriding Clerk interfaces for custom types
  docs/guides/custom-types.mdx
  docs/manifest.json
Labels: deploy-preview

#1457 Update instructions for handling Account Portal fallback redirects
  docs/customization/account-portal/direct-links.mdx
  docs/deployments/clerk-environment-variables
  docs/deployments/clerk-environment-variables.mdx
Labels: deploy-preview

#1446 Update import path for `useLocalCredentials`
  docs/references/expo/local-credentials.mdx
  docs/references/expo/use-local-credentials.mdx
Labels: deploy-preview

#1476 Fix typo in biometricType value for Expo
  docs/references/expo/use-local-credentials.mdx
Labels: deploy-preview

#1478 Fix `biometricType` type typo
  docs/references/expo/use-local-credentials.mdx
Labels: deploy-preview

#1469 Rename OAuth for Expo applications to OAuth for native applications
  docs/authentication/social-connections/oauth.mdx
Labels: deploy-preview

#1482 chore: Improve custom OAuth edge cases section
  docs/authentication/social-connections/custom-provider.mdx
Labels: deploy-preview

#1473 Add `deleteUserProfileImage` to Backend SDK reference
  docs/manifest.json
  docs/references/backend/user/delete-user-profile-image.mdx
  docs/references/javascript/user/user.mdx
Labels: deploy-preview

#1461 Update descriptions for hook reference docs
  docs/references/nextjs/get-auth.mdx
  docs/references/react/use-auth.mdx
  docs/references/react/use-clerk.mdx
  docs/references/react/use-organization-list.mdx
  docs/references/react/use-sign-in.mdx
  docs/references/react/use-sign-up.mdx
  docs/references/react/use-user.mdx
Labels: deploy-preview

#1468 docs(astro): Add localization and appearance examples for Astro
  docs/customization/layout.mdx
  docs/customization/localization.mdx
  docs/customization/themes.mdx
  docs/customization/variables.mdx
Labels: deploy-preview

#1484 docs(sdk): Add a warning about avoiding exposing secret key to the frontend
  docs/references/sdk/conventions.mdx
Labels: deploy-preview

#1485 Satellite domain docs fixes
  docs/advanced-usage/satellite-domains.mdx
Labels: deploy-preview

#1490 (/sign-up-sign-in-options) Add section about resetting a user's MFA
  docs/authentication/configuration/sign-up-sign-in-options.mdx
  docs/test.mdx
Labels: deploy-preview

#1280 Add locked to User class
  docs/references/backend/user/ban-user.mdx
  docs/references/backend/user/create-user.mdx
  docs/references/backend/user/get-user-list.mdx
  docs/references/backend/user/get-user.mdx
  docs/references/backend/user/lock-user.mdx
  docs/references/backend/user/unban-user.mdx
  docs/references/backend/user/unlock-user.mdx
  docs/references/backend/user/update-user-metadata.mdx
  docs/references/backend/user/update-user-profile-image.mdx
  docs/references/backend/user/update-user.mdx
Labels: Blocked

#1343 update force-organizations.mdx
  docs/guides/force-organizations.mdx
Labels: deploy-preview

#1497 feat: Add new organizationId option to getToken()
  docs/references/javascript/session.mdx
Labels: deploy-preview

#1491 docs(gatsby-plugin-clerk): Clean up Gatsby SDK references
  docs/authentication/social-connections/oauth.mdx
  docs/backend-requests/handling/gatsby.mdx
  docs/backend-requests/handling/nodejs.mdx
  docs/backend-requests/overview.mdx
  docs/components/authentication/sign-in.mdx
  docs/components/authentication/sign-up.mdx
  docs/components/clerk-provider.mdx
  docs/components/unstyled/sign-in-button.mdx
  docs/components/unstyled/sign-in-with-metamask.mdx
  docs/components/unstyled/sign-out-button.mdx
  docs/components/unstyled/sign-up-button.mdx
  docs/custom-flows/email-password.mdx
  docs/custom-flows/email-sms-otp.mdx
  docs/custom-flows/error-handling.mdx
  docs/custom-flows/forgot-password.mdx
  docs/custom-flows/manage-sms-based-mfa.mdx
  docs/custom-flows/manage-totp-based-mfa.mdx
  docs/custom-flows/sign-out.mdx
  docs/customization/organization-profile.mdx
  docs/customization/overview.mdx
  docs/customization/user-profile.mdx
  docs/index.mdx
  docs/integrations/databases/firebase.mdx
  docs/manifest.json
  docs/manifest.schema.json
  docs/organizations/creating-organizations.mdx
  docs/organizations/custom-organization-switcher.mdx
  docs/organizations/inviting-users.mdx
  docs/organizations/manage-invitations.mdx
  docs/organizations/manage-membership-requests.mdx
  docs/organizations/managing-roles.mdx
  docs/organizations/updating-organizations.mdx
  docs/organizations/verify-user-permissions.mdx
  docs/organizations/viewing-memberships.mdx
  docs/quickstarts/gatsby.mdx
  docs/quickstarts/overview.mdx
  docs/quickstarts/setup-clerk.mdx
  docs/references/gatsby/with-server-auth.mdx
  docs/references/overview.mdx
  docs/telemetry.mdx
  docs/troubleshooting/create-a-minimal-reproduction.mdx
  docs/upgrade-guides/core-2/overview.mdx
  docs/upgrade-guides/upgrading-from-v2-to-v3.mdx
  docs/users/metadata.mdx
Labels: deploy-preview

#1500 Update component overview
  docs/components/overview.mdx
Labels: deploy-preview

#1486 docs(astro): Add reference to hybrid rendering in Astro
  docs/manifest.json
  docs/quickstarts/astro.mdx
  docs/references/astro/hybrid-rendering.mdx
Labels: deploy-preview

#1502 Expo native requires custom flows over UI components
  docs/quickstarts/expo.mdx
Labels: deploy-preview

#1492 Add docs for Hugging Face Auth provider
  docs/authentication/social-connections/huggingface.mdx
  docs/authentication/social-connections/overview.mdx
  docs/manifest.json
  public/images/authentication-providers/huggingface/client-id-client-secret.png
  public/images/authentication-providers/huggingface/create-application.png
  public/images/authentication-providers/huggingface/scopes-and-redirect-url.png
  public/images/logos/auth_providers/huggingface.svg
Labels: deploy-preview

#1503 Fixes ACS URL meaning on Azure and Okta guides
  docs/authentication/saml/azure.mdx
  docs/authentication/saml/okta.mdx
Labels: deploy-preview

#1498 Add guide about Organization Workspaces in the Clerk Dashboard
  docs/manifest.json
  docs/organizations/organization-workspaces.mdx
Labels: deploy-preview

#1489 Fix Supabase SSR example
  docs/integrations/databases/supabase.mdx
Labels: deploy-preview

#1423 Add nextjs example to proxy config
  docs/advanced-usage/using-proxies.mdx
  docs/authentication/configuration/session-options.mdx
Labels: deploy-preview

#1424 Add strict-dynamic CSP docs
  docs/security/clerk-csp.mdx
Labels: deploy-preview
