Repository clerk/clerk-docs, pull requests merged in 2024-01, with the labels that each got.

#581 Add callout to `OrganizationSwitcher`
  docs/organizations/verify-user-permissions.mdx
Labels: deploy-preview

#496 feat: adds telemetry page
  docs/components/clerk-provider.mdx
  docs/manifest.json
  docs/references/javascript/clerk/clerk.mdx
  docs/references/nextjs/current-user.mdx
  docs/references/nextjs/read-session-data.mdx
  docs/references/nextjs/route-handlers.mdx
  docs/references/nextjs/server-actions.mdx
  docs/telemetry.mdx
Labels: deploy-preview

#613 DOCS-778 differentiate between the component reference and JS reference for the SignIn component
  docs/components/authentication/sign-in.mdx
  docs/references/javascript/clerk/sign-in.mdx
Labels: deploy-preview

#617 sync tab instances for this page
  docs/custom-flows/email-sms-otp.mdx
Labels: deploy-preview

#597 Update user-lock-guide.mdx
  docs/custom-flows/error-handling.mdx
  docs/security/unlock-user-accounts.mdx
  docs/security/user-lock-guide.mdx
Labels: deploy-preview

#598 "force organizations" guide suggestions
  docs/guides/force-organizations.mdx
  docs/manifest.json
  docs/organizations/overview.mdx
Labels: deploy-preview

#591 feat: Guide for forcing organizations
  docs/guides/force-organizations.mdx
  docs/manifest.json
  docs/organizations/overview.mdx
Labels: deploy-preview

#624 Retheme updates
  docs/components/customization/organization-profile.mdx
  docs/components/customization/variables.mdx
Labels: release-on-v5

#618 DOCS-5249 introduce the getOrganizationInvitationList page
  docs/manifest.json
  docs/references/backend/organization/get-organization-invitation-list.mdx
  docs/references/backend/overview.mdx
Labels: release-on-v5

#634 Remove with clerk middleware
  docs/references/nextjs/with-clerk-middleware.mdx
Labels: release-on-v5

#623 DOCS-5154 add getOrganizationMemberships to User class
  docs/manifest.json
  docs/organizations/managing-roles.mdx
  docs/organizations/updating-organizations.mdx
  docs/organizations/viewing-memberships.mdx
  docs/references/javascript/clerk/clerk.mdx
  docs/references/javascript/clerk/organization-methods.mdx
  docs/references/javascript/organization/domains.mdx
  docs/references/javascript/organization/invitations.mdx
  docs/references/javascript/organization/members.mdx
  docs/references/javascript/organization/membership-request.mdx
  docs/references/javascript/types/clerk-paginated-response.mdx
  docs/references/javascript/user/user.mdx
Labels: deploy-preview, release-on-v5

#627 v5 javascript updates
  docs/components/authentication/sign-in.mdx
  docs/components/authentication/sign-up.mdx
  docs/custom-flows/oauth-connections.mdx
  docs/custom-flows/saml-connections.mdx
  docs/organizations/creating-organizations.mdx
  docs/organizations/inviting-users.mdx
  docs/organizations/managing-roles.mdx
  docs/references/backend/overview.mdx
  docs/references/javascript/clerk/clerk.mdx
  docs/references/javascript/clerk/create-organization.mdx
  docs/references/javascript/clerk/organization-methods.mdx
  docs/references/javascript/clerk/redirect-methods.mdx
  docs/references/javascript/clerk/session-methods.mdx
  docs/references/javascript/clerk/sign-in.mdx
  docs/references/javascript/clerk/sign-up.mdx
  docs/references/javascript/external-account.mdx
  docs/references/javascript/organization/invitations.mdx
  docs/references/javascript/organization/members.mdx
  docs/references/javascript/organization/organization.mdx
  docs/references/javascript/sign-up/web3-verification.mdx
  docs/references/javascript/user/user.mdx
  docs/references/nextjs/server-actions.mdx
  docs/references/react/use-organization-list.mdx
  docs/testing/cypress.mdx
Labels: deploy-preview, release-on-v5

#619 v5 updates
  docs/backend-requests/handling/nodejs.mdx
  docs/components/clerk-provider.mdx
  docs/manifest.json
  docs/organizations/managing-roles.mdx
  docs/organizations/updating-organizations.mdx
  docs/organizations/viewing-memberships.mdx
  docs/quickstarts/javascript.mdx
  docs/references/backend/organization/get-organization-invitation-list.mdx
  docs/references/backend/overview.mdx
  docs/references/backend/sessions/authenticate-request.mdx
  docs/references/javascript/clerk/clerk.mdx
  docs/references/javascript/clerk/organization-methods.mdx
  docs/references/javascript/organization/domains.mdx
  docs/references/javascript/organization/invitations.mdx
  docs/references/javascript/organization/members.mdx
  docs/references/javascript/organization/membership-request.mdx
  docs/references/javascript/organization/organization.mdx
  docs/references/javascript/overview.mdx
  docs/references/javascript/types/clerk-paginated-response.mdx
  docs/references/javascript/user/user.mdx
  docs/references/nextjs/auth-middleware.mdx
  docs/references/remix/clerk-app.mdx
Labels: release-on-v5

#620 Remove references to createEmail function
  docs/manifest.json
  docs/references/backend/emails/create-email.mdx
  docs/references/backend/overview.mdx
  docs/references/nodejs/overview.mdx
  docs/references/ruby/available-methods.mdx
Labels: release-on-v5

#649 Updated quickstart for v5
  docs/quickstarts/nextjs.mdx
Labels: deploy-preview

#645 Add Inngest guide
  docs/integrations/webhooks/inngest.mdx
  docs/manifest.json
  public/images/integrations/inngest/inngest-clerk-events.webp
  public/images/integrations/inngest/inngest-dev-server.webp
  public/images/integrations/inngest/inngest-permissions-dialog.webp
  public/images/integrations/inngest/inngest-replay-event.webp
  public/images/integrations/inngest/inngest-send-to-dev-server.webp
  public/images/integrations/inngest/webhook-create.webp
  public/images/integrations/inngest/webhook-endpoint-connected.webp
  public/images/integrations/inngest/webhook-page.webp
  public/images/integrations/inngest/webhook-transformation-template.webp
Labels: deploy-preview

#648 Add docs about blocking email subaddressing for Google OAuth
  docs/authentication/social-connections/google.mdx
  public/images/authentication-providers/google/google-block-email-subaddresses.webp
Labels: deploy-preview

#656 Fix broken image for Google block email subaddresses
  docs/authentication/social-connections/google.mdx
Labels: deploy-preview

#657 chore: Add section about publishing status to Google OAuth page
  docs/authentication/social-connections/google.mdx
  docs/manifest.json
  public/images/authentication-providers/google/oauth_google_consent_screen.png
Labels: deploy-preview

#667 DOCS-136 update convex guide
  docs/integrations/databases/convex.mdx
  docs/quickstarts/react.mdx
Labels: deploy-preview

#668 DOCS-780 update org switcher guide
  docs/manifest.json
  docs/organizations/custom-organization-switcher.mdx
  docs/organizations/multiple-orgs.mdx
Labels: deploy-preview
